// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjbpvjyxdjciyobnbhrw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqYnB2anl4ZGpjaXlvYm5iaHJ3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU0OTMxODIsImV4cCI6MjA2MTA2OTE4Mn0.dTROxzYh9Nnn90u7oN6fiFGCco6EOKgLDCIia2vbqRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);